// GET USER
GET https://api-konser-559917148272.us-central1.run.app/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtYSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJwaG90byI6bnVsbCwidW11ciI6MjUsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMzFUMDk6MDk6MzYuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMzFUMDk6MDk6MzYuMDAwWiIsImlhdCI6MTc0ODY4MjU4MCwiZXhwIjoxNzQ4NzY4OTgwfQ._7XyPSH38bzkZJkNHR51MbKEEt9e31jXVtu3uENPYDM

# ###

# // UPDATE ADMIN BY ID
# PATCH  http://localhost:5000/admin/1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtYSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTEwVDAyOjQ1OjExLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTEwVDAzOjAxOjM1LjAwMFoiLCJpYXQiOjE3NDY4NDYxMjQsImV4cCI6MTc0Njg0NjQyNH0.IC5Fz3g1k-68FHDrEB20E-2rz1w6nath_yQygsEgrYc

# {
# "nama": "test updated", 
# "email": "test@test.com",
# "pass": "test"
# }

# ###

# // DELETE ADMIN BY ID
# DELETE http://localhost:5000/admin/0

###
// REGISTER
POST https://api-konser-559917148272.us-central1.run.app/register
Content-Type: application/json

{
"nama": "admin",
"email": "admin@gmail.com",
"umur": 25,
"pass": "admin"
}

###

// LOGIN
POST https://api-konser-559917148272.us-central1.run.app/login 
Content-Type: application/json

{
"email": "admin@gmail.com",
"pass": "admin"
}

###

// LOGOUT
DELETE https://api-konser-559917148272.us-central1.run.app/logout

###

// ADD TIKET
POST https://api-konser-559917148272.us-central1.run.app/tiket
Content-Type: application/json

{
"nama": "Summerfest",
"tanggal": "30 Desember 2025",
"harga": "200000",
"quota": "5"
}

###

// GET TIKET
GET https://api-konser-559917148272.us-central1.run.app/tiket
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtYSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJ1bXVyIjoyNSwiY3JlYXRlZEF0IjoiMjAyNS0wNS0zMFQwMToyNDo1My4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0zMFQwNTo0NToyMC4wMDBaIiwiaWF0IjoxNzQ4NTg0NDUzLCJleHAiOjE3NDg2NzA4NTN9.qxbR747omsM4f7ldMT75RV9_DufJ2fxnjtAlUD4gDrM

###

// GET TIKET BY ID
GET https://api-konser-559917148272.us-central1.run.app/tiket/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtYSI6InVzZXIiLCJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0xOVQxNzowNzozNS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMFQwMTo0NzoyMi4wMDBaIiwiaWF0IjoxNzQ3NzA1ODI2LCJleHAiOjE3NDc3OTIyMjZ9._bwHsU_1k-ArmjSx2ba2PX5cEZT0Y3FF3q0HfhUNueA

###

// UPDATE TIKET BY ID
PATCH  https://api-konser-559917148272.us-central1.run.app/tiket/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtYSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTEyVDA4OjI0OjQ1LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTEyVDA4OjMxOjAyLjAwMFoiLCJpYXQiOjE3NDcwNjM3MTUsImV4cCI6MTc0NzA2NDAxNX0.CDXK3KN7UWVDEedYB4SLhNpOTmhKVgks_2SuBDGe24k

{
"harga": 120000,
"quota": "5"
}

###

// DELETE TIKET BY ID
DELETE http://localhost:5000/tiket/1

###

// ORDER TIKET
PATCH  https://api-konser-559917148272.us-central1.run.app/order/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtYSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJwaG90byI6bnVsbCwidW11ciI6MjUsImNyZWF0ZWRBdCI6IjIwMjUtMDYtMDFUMDA6NDE6NTUuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDYtMDFUMDA6NDE6NTUuMDAwWiIsImlhdCI6MTc0ODczODUxNywiZXhwIjoxNzQ4ODI0OTE3fQ.NBvJTStrpzIpJyDH4JiZPYbOqVBw-0MoBnZ8HLYR_x8

{
    "nama": "popo",
    "umur": "20",
    "email": "popo@gmail.com"
}

###

// ADD KONSER
POST https://api-konser-559917148272.us-central1.run.app/konser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtYSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJwaG90byI6bnVsbCwidW11ciI6MjUsImNyZWF0ZWRBdCI6IjIwMjUtMDYtMDFUMDA6NDE6NTUuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDYtMDFUMDA6NDE6NTUuMDAwWiIsImlhdCI6MTc0ODczODUxNywiZXhwIjoxNzQ4ODI0OTE3fQ.NBvJTStrpzIpJyDH4JiZPYbOqVBw-0MoBnZ8HLYR_x8

{
"nama": "HELL",
"poster": "https://marketplace.canva.com/EAGLxKj0I2M/2/0/1131w/canva-merah-dan-putih-modern-konser-spesial-kemerdekaan-poster-Rw45qHDhqD8.jpg",
"tanggal": "???",
"lokasi": "HELL",
"bintangtamu": "DEMON",
"harga": 400000,
"quota": 1500
}

###

// GET KONSER
GET https://api-konser-559917148272.us-central1.run.app/konser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtYSI6InRlc3QxIiwiZW1haWwiOiJ0ZXN0MSIsInVtdXIiOjI1LCJjcmVhdGVkQXQiOiIyMDI1LTA1LTI3VDA0OjAwOjI5LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI3VDA0OjAzOjE1LjAwMFoiLCJpYXQiOjE3NDgzMjk4MjMsImV4cCI6MTc0ODQxNjIyM30.ESKGNt3O4r2kNsQS7XlVpUP3OMGXLqCmRNHvWC3m0E4

###

// GET KONSER BY ID
GET http://localhost:5000/konser/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtYSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTEyVDA4OjI0OjQ1LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTEyVDE1OjM1OjQ3LjAwMFoiLCJpYXQiOjE3NDcwNjYyMjYsImV4cCI6MTc0NzE1MjYyNn0.5rfL3BtxKMrKFCb9v5EQXCCuDJMmLyYHwNq7XVTfoyE

###

// UPDATE KONSER BY ID
PATCH  https://api-konser-559917148272.us-central1.run.app/konser/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtYSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJ1bXVyIjoyNSwiY3JlYXRlZEF0IjoiMjAyNS0wNS0zMFQwMToyNDo1My4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0zMFQwNDoxMzowNC4wMDBaIiwiaWF0IjoxNzQ4NTc5NjM1LCJleHAiOjE3NDg2NjYwMzV9.X0rYWlkDtjf3Ey-e8Tw_kFGAqnC26AtprQa6yUeFTA4

{
"nama": "test tiket",
"tanggal": "21 maret 2024",
"lokasi": "Jaksel",
"bintangtamu": "???"
}

###

// DELETE KONSER BY ID
DELETE http://localhost:5000/konser/1

###

// ADD PENGUNJUNG
POST http://localhost:5000/pengunjung
Content-Type: application/json

{
"nama": "Budiman",
"umur": "21",
"email": "manusiabudiman1@gmail.com"
}

###

// GET PENGUNJUNG
GET http://localhost:5000/pengunjung
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtYSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJwaG90byI6bnVsbCwidW11ciI6MjUsImNyZWF0ZWRBdCI6IjIwMjUtMDYtMDFUMDA6NDE6NTUuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDYtMDFUMDA6NDE6NTUuMDAwWiIsImlhdCI6MTc0ODczODUxNywiZXhwIjoxNzQ4ODI0OTE3fQ.NBvJTStrpzIpJyDH4JiZPYbOqVBw-0MoBnZ8HLYR_x8

###

// GET PENGUNJUNG BY ID
GET http://localhost:5000/pengunjung/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtYSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTEyVDA4OjI0OjQ1LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTEyVDE1OjM1OjQ3LjAwMFoiLCJpYXQiOjE3NDcwNjYyMjYsImV4cCI6MTc0NzE1MjYyNn0.5rfL3BtxKMrKFCb9v5EQXCCuDJMmLyYHwNq7XVTfoyE

###

// UPDATE PENGUNJUNG BY ID
PATCH  http://localhost:5000/pengunjung/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtYSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTEyVDA4OjI0OjQ1LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTEyVDE1OjM1OjQ3LjAwMFoiLCJpYXQiOjE3NDcwNjYyMjYsImV4cCI6MTc0NzE1MjYyNn0.5rfL3BtxKMrKFCb9v5EQXCCuDJMmLyYHwNq7XVTfoyE

{
"nama": "budiman",
"umur": "25",
"email": "manusiabudiman1@gmail.com"
}

###

// DELETE PENGUNJUNG BY ID
DELETE http://localhost:5000/pengunjung/1